## static_territories
UPDATE static_territories SET tr_name_ru='Африка' WHERE tr_iso_nr='2';
UPDATE static_territories SET tr_name_ru='Океания' WHERE tr_iso_nr='9';
UPDATE static_territories SET tr_name_ru='Северная и Южная Америка' WHERE tr_iso_nr='19';
UPDATE static_territories SET tr_name_ru='Азия' WHERE tr_iso_nr='142';
UPDATE static_territories SET tr_name_ru='Европа' WHERE tr_iso_nr='150';
UPDATE static_territories SET tr_name_ru='Восточная Азия' WHERE tr_iso_nr='30';
UPDATE static_territories SET tr_name_ru='Юго-Восточная Азия' WHERE tr_iso_nr='35';
UPDATE static_territories SET tr_name_ru='Центральная Азия' WHERE tr_iso_nr='143';
UPDATE static_territories SET tr_name_ru='Западная Азия' WHERE tr_iso_nr='145';
UPDATE static_territories SET tr_name_ru='Южная Европа' WHERE tr_iso_nr='39';
UPDATE static_territories SET tr_name_ru='Восточная Европа' WHERE tr_iso_nr='151';
UPDATE static_territories SET tr_name_ru='Северная Европа' WHERE tr_iso_nr='154';
UPDATE static_territories SET tr_name_ru='Западная Европа' WHERE tr_iso_nr='155';
UPDATE static_territories SET tr_name_ru='Южная Америка' WHERE tr_iso_nr='5';
UPDATE static_territories SET tr_name_ru='Центральная Америка' WHERE tr_iso_nr='13';
UPDATE static_territories SET tr_name_ru='Северная Америка' WHERE tr_iso_nr='21';
UPDATE static_territories SET tr_name_ru='Карибский бассейн' WHERE tr_iso_nr='29';
UPDATE static_territories SET tr_name_ru='Западная Африка' WHERE tr_iso_nr='11';
UPDATE static_territories SET tr_name_ru='Восточная Африка' WHERE tr_iso_nr='14';
UPDATE static_territories SET tr_name_ru='Северная Африка' WHERE tr_iso_nr='15';
UPDATE static_territories SET tr_name_ru='Центральная Африка' WHERE tr_iso_nr='17';
UPDATE static_territories SET tr_name_ru='Южная часть Африки' WHERE tr_iso_nr='18';
UPDATE static_territories SET tr_name_ru='Австралия и Новая Зеландия' WHERE tr_iso_nr='53';
UPDATE static_territories SET tr_name_ru='Меланезия' WHERE tr_iso_nr='54';
UPDATE static_territories SET tr_name_ru='Микронезия' WHERE tr_iso_nr='57';
UPDATE static_territories SET tr_name_ru='Полинезия' WHERE tr_iso_nr='61';
UPDATE static_territories SET tr_name_ru='Южная Азия' WHERE tr_iso_nr='34';
UPDATE static_territories SET tr_name_ru='Латинская Америка и Карибский бассейн' WHERE tr_iso_nr='419';


## static_countries
UPDATE static_countries SET cn_short_ru='Андорра' WHERE cn_iso_2='AD';
UPDATE static_countries SET cn_short_ru='Объединенные Арабские Эмираты' WHERE cn_iso_2='AE';
UPDATE static_countries SET cn_short_ru='Афганистан' WHERE cn_iso_2='AF';
UPDATE static_countries SET cn_short_ru='Антигуа и Барбуда' WHERE cn_iso_2='AG';
UPDATE static_countries SET cn_short_ru='Ангилья' WHERE cn_iso_2='AI';
UPDATE static_countries SET cn_short_ru='Албания' WHERE cn_iso_2='AL';
UPDATE static_countries SET cn_short_ru='Армения' WHERE cn_iso_2='AM';
UPDATE static_countries SET cn_short_ru='Нидерландские Антилы' WHERE cn_iso_2='AN';
UPDATE static_countries SET cn_short_ru='Ангола' WHERE cn_iso_2='AO';
UPDATE static_countries SET cn_short_ru='Антарктида' WHERE cn_iso_2='AQ';
UPDATE static_countries SET cn_short_ru='Аргентина' WHERE cn_iso_2='AR';
UPDATE static_countries SET cn_short_ru='Американское Самоа' WHERE cn_iso_2='AS';
UPDATE static_countries SET cn_short_ru='Австрия' WHERE cn_iso_2='AT';
UPDATE static_countries SET cn_short_ru='Австралия' WHERE cn_iso_2='AU';
UPDATE static_countries SET cn_short_ru='Аруба' WHERE cn_iso_2='AW';
UPDATE static_countries SET cn_short_ru='Азербайджан' WHERE cn_iso_2='AZ';
UPDATE static_countries SET cn_short_ru='Босния и Герцеговина' WHERE cn_iso_2='BA';
UPDATE static_countries SET cn_short_ru='Барбадос' WHERE cn_iso_2='BB';
UPDATE static_countries SET cn_short_ru='Бангладеш' WHERE cn_iso_2='BD';
UPDATE static_countries SET cn_short_ru='Бельгия' WHERE cn_iso_2='BE';
UPDATE static_countries SET cn_short_ru='Буркина-Фасо' WHERE cn_iso_2='BF';
UPDATE static_countries SET cn_short_ru='Болгария' WHERE cn_iso_2='BG';
UPDATE static_countries SET cn_short_ru='Бахрейн' WHERE cn_iso_2='BH';
UPDATE static_countries SET cn_short_ru='Бурунди' WHERE cn_iso_2='BI';
UPDATE static_countries SET cn_short_ru='Бенин' WHERE cn_iso_2='BJ';
UPDATE static_countries SET cn_short_ru='Бермуды' WHERE cn_iso_2='BM';
UPDATE static_countries SET cn_short_ru='Бруней-Даруссалам' WHERE cn_iso_2='BN';
UPDATE static_countries SET cn_short_ru='Боливия' WHERE cn_iso_2='BO';
UPDATE static_countries SET cn_short_ru='Бразилия' WHERE cn_iso_2='BR';
UPDATE static_countries SET cn_short_ru='Багамы' WHERE cn_iso_2='BS';
UPDATE static_countries SET cn_short_ru='Бутан' WHERE cn_iso_2='BT';
UPDATE static_countries SET cn_short_ru='Остров Буве' WHERE cn_iso_2='BV';
UPDATE static_countries SET cn_short_ru='Ботсвана' WHERE cn_iso_2='BW';
UPDATE static_countries SET cn_short_ru='Беларусь' WHERE cn_iso_2='BY';
UPDATE static_countries SET cn_short_ru='Белиз' WHERE cn_iso_2='BZ';
UPDATE static_countries SET cn_short_ru='Канада' WHERE cn_iso_2='CA';
UPDATE static_countries SET cn_short_ru='Кокосовые (Килинг) острова' WHERE cn_iso_2='CC';
UPDATE static_countries SET cn_short_ru='Конго' WHERE cn_iso_2='CD';
UPDATE static_countries SET cn_short_ru='Центрально-Африканская Республика' WHERE cn_iso_2='CF';
UPDATE static_countries SET cn_short_ru='Конго' WHERE cn_iso_2='CG';
UPDATE static_countries SET cn_short_ru='Швейцария' WHERE cn_iso_2='CH';
UPDATE static_countries SET cn_short_ru="Кот д'Ивуар" WHERE cn_iso_2='CI';
UPDATE static_countries SET cn_short_ru='Острова Кука' WHERE cn_iso_2='CK';
UPDATE static_countries SET cn_short_ru='Чили' WHERE cn_iso_2='CL';
UPDATE static_countries SET cn_short_ru='Камерун' WHERE cn_iso_2='CM';
UPDATE static_countries SET cn_short_ru='Китай' WHERE cn_iso_2='CN';
UPDATE static_countries SET cn_short_ru='Колумбия' WHERE cn_iso_2='CO';
UPDATE static_countries SET cn_short_ru='Коста-Рика' WHERE cn_iso_2='CR';
UPDATE static_countries SET cn_short_ru='Сербия и Черногория' WHERE cn_iso_2='CS';
UPDATE static_countries SET cn_short_ru='Куба' WHERE cn_iso_2='CU';
UPDATE static_countries SET cn_short_ru='Кабо-Верде' WHERE cn_iso_2='CV';
UPDATE static_countries SET cn_short_ru='Остров Рождества' WHERE cn_iso_2='CX';
UPDATE static_countries SET cn_short_ru='Кипр' WHERE cn_iso_2='CY';
UPDATE static_countries SET cn_short_ru='Чешская Республика' WHERE cn_iso_2='CZ';
UPDATE static_countries SET cn_short_ru='Германия' WHERE cn_iso_2='DE';
UPDATE static_countries SET cn_short_ru='Джибути' WHERE cn_iso_2='DJ';
UPDATE static_countries SET cn_short_ru='Дания' WHERE cn_iso_2='DK';
UPDATE static_countries SET cn_short_ru='Доминика' WHERE cn_iso_2='DM';
UPDATE static_countries SET cn_short_ru='Доминиканская Республика' WHERE cn_iso_2='DO';
UPDATE static_countries SET cn_short_ru='Алжир' WHERE cn_iso_2='DZ';
UPDATE static_countries SET cn_short_ru='Эквадор' WHERE cn_iso_2='EC';
UPDATE static_countries SET cn_short_ru='Эстония' WHERE cn_iso_2='EE';
UPDATE static_countries SET cn_short_ru='Египет' WHERE cn_iso_2='EG';
UPDATE static_countries SET cn_short_ru='Западная Сахара' WHERE cn_iso_2='EH';
UPDATE static_countries SET cn_short_ru='Эритрея' WHERE cn_iso_2='ER';
UPDATE static_countries SET cn_short_ru='Испания' WHERE cn_iso_2='ES';
UPDATE static_countries SET cn_short_ru='Эфиопия' WHERE cn_iso_2='ET';
UPDATE static_countries SET cn_short_ru='Финляндия' WHERE cn_iso_2='FI';
UPDATE static_countries SET cn_short_ru='Фиджи' WHERE cn_iso_2='FJ';
UPDATE static_countries SET cn_short_ru='Фолклендские острова' WHERE cn_iso_2='FK';
UPDATE static_countries SET cn_short_ru='Микронезия, федеративные штаты' WHERE cn_iso_2='FM';
UPDATE static_countries SET cn_short_ru='Фарерские острова' WHERE cn_iso_2='FO';
UPDATE static_countries SET cn_short_ru='Франция' WHERE cn_iso_2='FR';
UPDATE static_countries SET cn_short_ru='Габон' WHERE cn_iso_2='GA';
UPDATE static_countries SET cn_short_ru='Соединенное Королевство' WHERE cn_iso_2='GB';
UPDATE static_countries SET cn_short_ru='Гренада' WHERE cn_iso_2='GD';
UPDATE static_countries SET cn_short_ru='Грузия' WHERE cn_iso_2='GE';
UPDATE static_countries SET cn_short_ru='Французская Гвиана' WHERE cn_iso_2='GF';
UPDATE static_countries SET cn_short_ru='Гана' WHERE cn_iso_2='GH';
UPDATE static_countries SET cn_short_ru='Гибралтар' WHERE cn_iso_2='GI';
UPDATE static_countries SET cn_short_ru='Гренландия' WHERE cn_iso_2='GL';
UPDATE static_countries SET cn_short_ru='Гамбия' WHERE cn_iso_2='GM';
UPDATE static_countries SET cn_short_ru='Гвинея' WHERE cn_iso_2='GN';
UPDATE static_countries SET cn_short_ru='Гваделупа' WHERE cn_iso_2='GP';
UPDATE static_countries SET cn_short_ru='Экваториальная Гвинея' WHERE cn_iso_2='GQ';
UPDATE static_countries SET cn_short_ru='Южная Джорджия и Южные Сандвичевы острова' WHERE cn_iso_2='GS';
UPDATE static_countries SET cn_short_ru='Греция' WHERE cn_iso_2='GR';
UPDATE static_countries SET cn_short_ru='Гватемала' WHERE cn_iso_2='GT';
UPDATE static_countries SET cn_short_ru='Гуам' WHERE cn_iso_2='GU';
UPDATE static_countries SET cn_short_ru='Гвинея-Бисау' WHERE cn_iso_2='GW';
UPDATE static_countries SET cn_short_ru='Гайана' WHERE cn_iso_2='GY';
UPDATE static_countries SET cn_short_ru='Гонконг' WHERE cn_iso_2='HK';
UPDATE static_countries SET cn_short_ru='Остров Херд и острова Макдональд' WHERE cn_iso_2='HM';
UPDATE static_countries SET cn_short_ru='Гондурас' WHERE cn_iso_2='HN';
UPDATE static_countries SET cn_short_ru='Хорватия' WHERE cn_iso_2='HR';
UPDATE static_countries SET cn_short_ru='Гаити' WHERE cn_iso_2='HT';
UPDATE static_countries SET cn_short_ru='Венгрия' WHERE cn_iso_2='HU';
UPDATE static_countries SET cn_short_ru='Индонезия' WHERE cn_iso_2='ID';
UPDATE static_countries SET cn_short_ru='Ирландия' WHERE cn_iso_2='IE';
UPDATE static_countries SET cn_short_ru='Израиль' WHERE cn_iso_2='IL';
UPDATE static_countries SET cn_short_ru='Индия' WHERE cn_iso_2='IN';
UPDATE static_countries SET cn_short_ru='Британская территория в Индийском океане' WHERE cn_iso_2='IO';
UPDATE static_countries SET cn_short_ru='Ирак' WHERE cn_iso_2='IQ';
UPDATE static_countries SET cn_short_ru='Иран' WHERE cn_iso_2='IR';
UPDATE static_countries SET cn_short_ru='Исландия' WHERE cn_iso_2='IS';
UPDATE static_countries SET cn_short_ru='Италия' WHERE cn_iso_2='IT';
UPDATE static_countries SET cn_short_ru='Ямайка' WHERE cn_iso_2='JM';
UPDATE static_countries SET cn_short_ru='Иордания' WHERE cn_iso_2='JO';
UPDATE static_countries SET cn_short_ru='Япония' WHERE cn_iso_2='JP';
UPDATE static_countries SET cn_short_ru='Кения' WHERE cn_iso_2='KE';
UPDATE static_countries SET cn_short_ru='Киргизия' WHERE cn_iso_2='KG';
UPDATE static_countries SET cn_short_ru='Камбоджа' WHERE cn_iso_2='KH';
UPDATE static_countries SET cn_short_ru='Кирибати' WHERE cn_iso_2='KI';
UPDATE static_countries SET cn_short_ru='Коморы' WHERE cn_iso_2='KM';
UPDATE static_countries SET cn_short_ru='Сен-Китс и Невис' WHERE cn_iso_2='KN';
UPDATE static_countries SET cn_short_ru='Северная Корея' WHERE cn_iso_2='KP';
UPDATE static_countries SET cn_short_ru='Южная Корея' WHERE cn_iso_2='KR';
UPDATE static_countries SET cn_short_ru='Кувейт' WHERE cn_iso_2='KW';
UPDATE static_countries SET cn_short_ru='Острова Кайман' WHERE cn_iso_2='KY';
UPDATE static_countries SET cn_short_ru='Казахстан' WHERE cn_iso_2='KZ';
UPDATE static_countries SET cn_short_ru='Лаос' WHERE cn_iso_2='LA';
UPDATE static_countries SET cn_short_ru='Ливан' WHERE cn_iso_2='LB';
UPDATE static_countries SET cn_short_ru='Сент-Люсия' WHERE cn_iso_2='LC';
UPDATE static_countries SET cn_short_ru='Лихтенштейн' WHERE cn_iso_2='LI';
UPDATE static_countries SET cn_short_ru='Шри-Ланка' WHERE cn_iso_2='LK';
UPDATE static_countries SET cn_short_ru='Либерия' WHERE cn_iso_2='LR';
UPDATE static_countries SET cn_short_ru='Лесото' WHERE cn_iso_2='LS';
UPDATE static_countries SET cn_short_ru='Литва' WHERE cn_iso_2='LT';
UPDATE static_countries SET cn_short_ru='Люксембург' WHERE cn_iso_2='LU';
UPDATE static_countries SET cn_short_ru='Латвия' WHERE cn_iso_2='LV';
UPDATE static_countries SET cn_short_ru='Ливийская Арабская Джамахирия' WHERE cn_iso_2='LY';
UPDATE static_countries SET cn_short_ru='Марокко' WHERE cn_iso_2='MA';
UPDATE static_countries SET cn_short_ru='Монако' WHERE cn_iso_2='MC';
UPDATE static_countries SET cn_short_ru='Молдова, республика' WHERE cn_iso_2='MD';
UPDATE static_countries SET cn_short_ru='Мадагаскар' WHERE cn_iso_2='MG';
UPDATE static_countries SET cn_short_ru='Маршалловы Острова' WHERE cn_iso_2='MH';
UPDATE static_countries SET cn_short_ru='Македония' WHERE cn_iso_2='MK';
UPDATE static_countries SET cn_short_ru='Мали' WHERE cn_iso_2='ML';
UPDATE static_countries SET cn_short_ru='Мьянма' WHERE cn_iso_2='MM';
UPDATE static_countries SET cn_short_ru='Монголия' WHERE cn_iso_2='MN';
UPDATE static_countries SET cn_short_ru='Макао' WHERE cn_iso_2='MO';
UPDATE static_countries SET cn_short_ru='Северные Марианские острова' WHERE cn_iso_2='MP';
UPDATE static_countries SET cn_short_ru='Мартиника' WHERE cn_iso_2='MQ';
UPDATE static_countries SET cn_short_ru='Мавритания' WHERE cn_iso_2='MR';
UPDATE static_countries SET cn_short_ru='Монтсеррат' WHERE cn_iso_2='MS';
UPDATE static_countries SET cn_short_ru='Мальта' WHERE cn_iso_2='MT';
UPDATE static_countries SET cn_short_ru='Маврикий' WHERE cn_iso_2='MU';
UPDATE static_countries SET cn_short_ru='Мальдивы' WHERE cn_iso_2='MV';
UPDATE static_countries SET cn_short_ru='Малави' WHERE cn_iso_2='MW';
UPDATE static_countries SET cn_short_ru='Мексика' WHERE cn_iso_2='MX';
UPDATE static_countries SET cn_short_ru='Малайзия' WHERE cn_iso_2='MY';
UPDATE static_countries SET cn_short_ru='Мозамбик' WHERE cn_iso_2='MZ';
UPDATE static_countries SET cn_short_ru='Намибия' WHERE cn_iso_2='NA';
UPDATE static_countries SET cn_short_ru='Новая Каледония' WHERE cn_iso_2='NC';
UPDATE static_countries SET cn_short_ru='Нигер' WHERE cn_iso_2='NE';
UPDATE static_countries SET cn_short_ru='Остров Норфолк' WHERE cn_iso_2='NF';
UPDATE static_countries SET cn_short_ru='Нигерия' WHERE cn_iso_2='NG';
UPDATE static_countries SET cn_short_ru='Никарагуа' WHERE cn_iso_2='NI';
UPDATE static_countries SET cn_short_ru='Нидерланды' WHERE cn_iso_2='NL';
UPDATE static_countries SET cn_short_ru='Норвегия' WHERE cn_iso_2='NO';
UPDATE static_countries SET cn_short_ru='Непал' WHERE cn_iso_2='NP';
UPDATE static_countries SET cn_short_ru='Науру' WHERE cn_iso_2='NR';
UPDATE static_countries SET cn_short_ru='Ниуэ' WHERE cn_iso_2='NU';
UPDATE static_countries SET cn_short_ru='Новая Зеландия' WHERE cn_iso_2='NZ';
UPDATE static_countries SET cn_short_ru='Оман' WHERE cn_iso_2='OM';
UPDATE static_countries SET cn_short_ru='Панама' WHERE cn_iso_2='PA';
UPDATE static_countries SET cn_short_ru='Перу' WHERE cn_iso_2='PE';
UPDATE static_countries SET cn_short_ru='Французская Полинезия' WHERE cn_iso_2='PF';
UPDATE static_countries SET cn_short_ru='Папуа - Новая Гвинея' WHERE cn_iso_2='PG';
UPDATE static_countries SET cn_short_ru='Филиппины' WHERE cn_iso_2='PH';
UPDATE static_countries SET cn_short_ru='Пакистан' WHERE cn_iso_2='PK';
UPDATE static_countries SET cn_short_ru='Польша' WHERE cn_iso_2='PL';
UPDATE static_countries SET cn_short_ru='Сент-Пьер и Микелон' WHERE cn_iso_2='PM';
UPDATE static_countries SET cn_short_ru='Питкерн' WHERE cn_iso_2='PN';
UPDATE static_countries SET cn_short_ru='Пуэрто-Рико' WHERE cn_iso_2='PR';
UPDATE static_countries SET cn_short_ru='Палестинская территория' WHERE cn_iso_2='PS';
UPDATE static_countries SET cn_short_ru='Португалия' WHERE cn_iso_2='PT';
UPDATE static_countries SET cn_short_ru='Палау' WHERE cn_iso_2='PW';
UPDATE static_countries SET cn_short_ru='Парагвай' WHERE cn_iso_2='PY';
UPDATE static_countries SET cn_short_ru='Катар' WHERE cn_iso_2='QA';
UPDATE static_countries SET cn_short_ru='Реюньон' WHERE cn_iso_2='RE';
UPDATE static_countries SET cn_short_ru='Румыния' WHERE cn_iso_2='RO';
UPDATE static_countries SET cn_short_ru='Россия' WHERE cn_iso_2='RU';
UPDATE static_countries SET cn_short_ru='Руанда' WHERE cn_iso_2='RW';
UPDATE static_countries SET cn_short_ru='Саудовская Аравия' WHERE cn_iso_2='SA';
UPDATE static_countries SET cn_short_ru='Соломоновы Острова' WHERE cn_iso_2='SB';
UPDATE static_countries SET cn_short_ru='Сейшелы' WHERE cn_iso_2='SC';
UPDATE static_countries SET cn_short_ru='Судан' WHERE cn_iso_2='SD';
UPDATE static_countries SET cn_short_ru='Швеция' WHERE cn_iso_2='SE';
UPDATE static_countries SET cn_short_ru='Сингапур' WHERE cn_iso_2='SG';
UPDATE static_countries SET cn_short_ru='Святая Елена' WHERE cn_iso_2='SH';
UPDATE static_countries SET cn_short_ru='Словения' WHERE cn_iso_2='SI';
UPDATE static_countries SET cn_short_ru='Шпицберген и Ян Майен' WHERE cn_iso_2='SJ';
UPDATE static_countries SET cn_short_ru='Словакия' WHERE cn_iso_2='SK';
UPDATE static_countries SET cn_short_ru='Сьерра-Леоне' WHERE cn_iso_2='SL';
UPDATE static_countries SET cn_short_ru='Сан-Марино' WHERE cn_iso_2='SM';
UPDATE static_countries SET cn_short_ru='Сенегал' WHERE cn_iso_2='SN';
UPDATE static_countries SET cn_short_ru='Сомали' WHERE cn_iso_2='SO';
UPDATE static_countries SET cn_short_ru='Суринам' WHERE cn_iso_2='SR';
UPDATE static_countries SET cn_short_ru='Сан-Томе и Принсипи' WHERE cn_iso_2='ST';
UPDATE static_countries SET cn_short_ru='Сальвадор' WHERE cn_iso_2='SV';
UPDATE static_countries SET cn_short_ru='Сирийская Арабская Республика' WHERE cn_iso_2='SY';
UPDATE static_countries SET cn_short_ru='Свазиленд' WHERE cn_iso_2='SZ';
UPDATE static_countries SET cn_short_ru='Острова Теркс и Кайкос' WHERE cn_iso_2='TC';
UPDATE static_countries SET cn_short_ru='Чад' WHERE cn_iso_2='TD';
UPDATE static_countries SET cn_short_ru='Французские Южные территории' WHERE cn_iso_2='TF';
UPDATE static_countries SET cn_short_ru='Того' WHERE cn_iso_2='TG';
UPDATE static_countries SET cn_short_ru='Таиланд' WHERE cn_iso_2='TH';
UPDATE static_countries SET cn_short_ru='Таджикистан' WHERE cn_iso_2='TJ';
UPDATE static_countries SET cn_short_ru='Токелау' WHERE cn_iso_2='TK';
UPDATE static_countries SET cn_short_ru='Туркмения' WHERE cn_iso_2='TM';
UPDATE static_countries SET cn_short_ru='Тунис' WHERE cn_iso_2='TN';
UPDATE static_countries SET cn_short_ru='Тонга' WHERE cn_iso_2='TO';
UPDATE static_countries SET cn_short_ru='Восточный Тимор' WHERE cn_iso_2='TP';
UPDATE static_countries SET cn_short_ru='Турция' WHERE cn_iso_2='TR';
UPDATE static_countries SET cn_short_ru='Тринидад и Тобаго' WHERE cn_iso_2='TT';
UPDATE static_countries SET cn_short_ru='Тувалу' WHERE cn_iso_2='TV';
UPDATE static_countries SET cn_short_ru='Тайвань (Китай)' WHERE cn_iso_2='TW';
UPDATE static_countries SET cn_short_ru='Танзания, объединенная республика' WHERE cn_iso_2='TZ';
UPDATE static_countries SET cn_short_ru='Украина' WHERE cn_iso_2='UA';
UPDATE static_countries SET cn_short_ru='Уганда' WHERE cn_iso_2='UG';
UPDATE static_countries SET cn_short_ru='Малые Тихоокеанские Отдаленные острова США' WHERE cn_iso_2='UM';
UPDATE static_countries SET cn_short_ru='Соединенные Штаты' WHERE cn_iso_2='US';
UPDATE static_countries SET cn_short_ru='Уругвай' WHERE cn_iso_2='UY';
UPDATE static_countries SET cn_short_ru='Узбекистан' WHERE cn_iso_2='UZ';
UPDATE static_countries SET cn_short_ru='Ватикан' WHERE cn_iso_2='VA';
UPDATE static_countries SET cn_short_ru='Сент-Винсент и Гренадины' WHERE cn_iso_2='VC';
UPDATE static_countries SET cn_short_ru='Венесуэла' WHERE cn_iso_2='VE';
UPDATE static_countries SET cn_short_ru='Виргинские острова, Британские' WHERE cn_iso_2='VG';
UPDATE static_countries SET cn_short_ru='Виргинские острова, США' WHERE cn_iso_2='VI';
UPDATE static_countries SET cn_short_ru='Вьетнам' WHERE cn_iso_2='VN';
UPDATE static_countries SET cn_short_ru='Вануату' WHERE cn_iso_2='VU';
UPDATE static_countries SET cn_short_ru='Уоллис и Футуна' WHERE cn_iso_2='WF';
UPDATE static_countries SET cn_short_ru='Самоа' WHERE cn_iso_2='WS';
UPDATE static_countries SET cn_short_ru='Йемен' WHERE cn_iso_2='YE';
UPDATE static_countries SET cn_short_ru='Майотта' WHERE cn_iso_2='YT';
UPDATE static_countries SET cn_short_ru='Югославия' WHERE cn_iso_2='YU';
UPDATE static_countries SET cn_short_ru='Южная Африка' WHERE cn_iso_2='ZA';
UPDATE static_countries SET cn_short_ru='Замбия' WHERE cn_iso_2='ZM';
UPDATE static_countries SET cn_short_ru='Зимбабве' WHERE cn_iso_2='ZW';
UPDATE static_countries SET cn_short_ru='Аландские острова' WHERE cn_iso_2='AX';
UPDATE static_countries SET cn_short_ru='Тимор-Лесте' WHERE cn_iso_2='TL';
UPDATE static_countries SET cn_short_ru='Черногория' WHERE cn_iso_2='ME';
UPDATE static_countries SET cn_short_ru='Сербия' WHERE cn_iso_2='RS';
UPDATE static_countries SET cn_short_ru='Джерси' WHERE cn_iso_2='JE';
UPDATE static_countries SET cn_short_ru='Гернси' WHERE cn_iso_2='GG';
UPDATE static_countries SET cn_short_ru='Остров Мэн' WHERE cn_iso_2='IM';
UPDATE static_countries SET cn_short_ru='Сен-Мартен' WHERE cn_iso_2='MF';
UPDATE static_countries SET cn_short_ru='Сен-Бартельми' WHERE cn_iso_2='BL';
UPDATE static_countries SET cn_short_ru='Бонайре, Синт-Эстатиус и Саба' WHERE cn_iso_2='BQ';
UPDATE static_countries SET cn_short_ru='Кюрасао' WHERE cn_iso_2='CW';
UPDATE static_countries SET cn_short_ru='Синт-Маартен' WHERE cn_iso_2='SX';
UPDATE static_countries SET cn_short_ru='Южный Судан' WHERE cn_iso_2='SS';


## static_country_zones
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='US' AND zn_code='AL';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='US' AND zn_code='AK';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='US' AND zn_code='AZ';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='US' AND zn_code='AR';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='US' AND zn_code='CA';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='US' AND zn_code='CO';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='US' AND zn_code='CT';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='US' AND zn_code='DE';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='US' AND zn_code='DC';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='US' AND zn_code='FL';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='US' AND zn_code='GA';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='US' AND zn_code='GU';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='US' AND zn_code='HI';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='US' AND zn_code='ID';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='US' AND zn_code='IL';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='US' AND zn_code='IN';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='US' AND zn_code='IA';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='US' AND zn_code='KS';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='US' AND zn_code='KY';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='US' AND zn_code='LA';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='US' AND zn_code='ME';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='US' AND zn_code='MD';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='US' AND zn_code='MA';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='US' AND zn_code='MI';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='US' AND zn_code='MN';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='US' AND zn_code='MS';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='US' AND zn_code='MO';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='US' AND zn_code='MT';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='US' AND zn_code='NE';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='US' AND zn_code='NV';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='US' AND zn_code='NH';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='US' AND zn_code='NJ';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='US' AND zn_code='NM';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='US' AND zn_code='NY';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='US' AND zn_code='NC';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='US' AND zn_code='ND';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='US' AND zn_code='OH';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='US' AND zn_code='OK';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='US' AND zn_code='OR';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='US' AND zn_code='PA';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='US' AND zn_code='PR';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='US' AND zn_code='RI';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='US' AND zn_code='SC';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='US' AND zn_code='SD';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='US' AND zn_code='TN';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='US' AND zn_code='TX';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='US' AND zn_code='UT';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='US' AND zn_code='VT';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='US' AND zn_code='VA';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='US' AND zn_code='WA';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='US' AND zn_code='WV';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='US' AND zn_code='WI';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='US' AND zn_code='WY';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='CA' AND zn_code='AB';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='CA' AND zn_code='BC';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='CA' AND zn_code='MB';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='CA' AND zn_code='NF';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='CA' AND zn_code='NB';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='CA' AND zn_code='NS';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='CA' AND zn_code='NT';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='CA' AND zn_code='NU';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='CA' AND zn_code='ON';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='CA' AND zn_code='PE';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='CA' AND zn_code='QC';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='CA' AND zn_code='SK';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='CA' AND zn_code='YT';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='DE' AND zn_code='NDS';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='DE' AND zn_code='BAW';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='DE' AND zn_code='BAY';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='DE' AND zn_code='BER';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='DE' AND zn_code='BRG';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='DE' AND zn_code='BRE';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='DE' AND zn_code='HAM';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='DE' AND zn_code='HES';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='DE' AND zn_code='MEC';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='DE' AND zn_code='NRW';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='DE' AND zn_code='RHE';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='DE' AND zn_code='SAR';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='DE' AND zn_code='SAS';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='DE' AND zn_code='SAC';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='DE' AND zn_code='SCN';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='DE' AND zn_code='THE';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='AT' AND zn_code='WI';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='AT' AND zn_code='NO';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='AT' AND zn_code='OO';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='AT' AND zn_code='SB';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='AT' AND zn_code='KN';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='AT' AND zn_code='ST';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='AT' AND zn_code='TI';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='AT' AND zn_code='BL';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='AT' AND zn_code='VB';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='CH' AND zn_code='AG';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='CH' AND zn_code='AI';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='CH' AND zn_code='AR';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='CH' AND zn_code='BE';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='CH' AND zn_code='BL';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='CH' AND zn_code='BS';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='CH' AND zn_code='FR';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='CH' AND zn_code='GE';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='CH' AND zn_code='GL';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='CH' AND zn_code='GR';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='CH' AND zn_code='JU';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='CH' AND zn_code='LU';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='CH' AND zn_code='NE';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='CH' AND zn_code='NW';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='CH' AND zn_code='OW';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='CH' AND zn_code='SG';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='CH' AND zn_code='SH';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='CH' AND zn_code='SO';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='CH' AND zn_code='SZ';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='CH' AND zn_code='TG';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='CH' AND zn_code='TI';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='CH' AND zn_code='UR';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='CH' AND zn_code='VD';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='CH' AND zn_code='VS';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='CH' AND zn_code='ZG';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='CH' AND zn_code='ZH';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='ES' AND zn_code='Alava';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='ES' AND zn_code='Malaga';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='ES' AND zn_code='Segovia';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='ES' AND zn_code='Granada';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='ES' AND zn_code='Jaen';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='ES' AND zn_code='Sevilla';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='ES' AND zn_code='Barcelona';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='ES' AND zn_code='Valencia';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='ES' AND zn_code='Alicante';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='ES' AND zn_code='Almeria';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='ES' AND zn_code='Asturias';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='ES' AND zn_code='Avila';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='ES' AND zn_code='Badajoz';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='ES' AND zn_code='Burgos';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='ES' AND zn_code='Caceres';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='ES' AND zn_code='Cadiz';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='ES' AND zn_code='Cantabria';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='ES' AND zn_code='Castellon';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='ES' AND zn_code='Ceuta';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='ES' AND zn_code='Ciudad Real';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='ES' AND zn_code='Cordoba';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='ES' AND zn_code='Cuenca';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='ES' AND zn_code='Girona';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='ES' AND zn_code='Las Palmas';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='ES' AND zn_code='Guadalajara';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='ES' AND zn_code='Guipuzcoa';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='ES' AND zn_code='Huelva';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='ES' AND zn_code='Huesca';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='ES' AND zn_code='A CoruГ±a';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='ES' AND zn_code='La Rioja';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='ES' AND zn_code='Leon';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='ES' AND zn_code='Lugo';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='ES' AND zn_code='Lleida';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='ES' AND zn_code='Madrid';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='ES' AND zn_code='Baleares';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='ES' AND zn_code='Murcia';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='ES' AND zn_code='Navarra';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='ES' AND zn_code='Ourense';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='ES' AND zn_code='Palencia';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='ES' AND zn_code='Pontevedra';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='ES' AND zn_code='Salamanca';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='ES' AND zn_code='Soria';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='ES' AND zn_code='Tarragona';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='ES' AND zn_code='Tenerife';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='ES' AND zn_code='Teruel';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='ES' AND zn_code='Toledo';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='ES' AND zn_code='Valladolid';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='ES' AND zn_code='Vizcaya';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='ES' AND zn_code='Zamora';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='ES' AND zn_code='Zaragoza';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='ES' AND zn_code='Melilla';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='MX' AND zn_code='AGS';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='MX' AND zn_code='BCS';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='MX' AND zn_code='BC';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='MX' AND zn_code='CAM';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='MX' AND zn_code='CHIS';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='MX' AND zn_code='CHIH';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='MX' AND zn_code='COAH';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='MX' AND zn_code='COL';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='MX' AND zn_code='DIF';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='MX' AND zn_code='DGO';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='MX' AND zn_code='GTO';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='MX' AND zn_code='GRO';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='MX' AND zn_code='HGO';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='MX' AND zn_code='JAL';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='MX' AND zn_code='MEX';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='MX' AND zn_code='MICH';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='MX' AND zn_code='MOR';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='MX' AND zn_code='NAY';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='MX' AND zn_code='NL';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='MX' AND zn_code='OAX';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='MX' AND zn_code='PUE';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='MX' AND zn_code='QRO';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='MX' AND zn_code='QROO';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='MX' AND zn_code='SLP';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='MX' AND zn_code='SIN';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='MX' AND zn_code='SON';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='MX' AND zn_code='TAB';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='MX' AND zn_code='TAMPS';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='MX' AND zn_code='TLAX';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='MX' AND zn_code='VER';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='MX' AND zn_code='YUC';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='MX' AND zn_code='ZAC';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='AU' AND zn_code='ACT';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='AU' AND zn_code='NSW';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='AU' AND zn_code='NT';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='AU' AND zn_code='QLD';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='AU' AND zn_code='SA';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='AU' AND zn_code='TAS';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='AU' AND zn_code='VIC';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='AU' AND zn_code='WA';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='AG';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='AL';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='AN';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='AO';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='AP';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='AQ';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='AR';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='AT';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='AV';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='BA';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='BG';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='BI';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='BL';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='BN';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='BO';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='BR';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='BS';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='BZ';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='CA';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='CB';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='CE';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='CH';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='CL';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='CN';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='CO';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='CR';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='CS';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='CT';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='CZ';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='EN';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='FE';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='FG';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='FI';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='FO';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='FR';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='GE';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='GO';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='GR';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='IM';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='IS';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='KR';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='LC';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='LE';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='LI';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='LO';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='LT';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='LU';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='MC';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='ME';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='MI';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='MN';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='MO';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='MS';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='MT';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='NA';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='NO';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='NU';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='OR';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='PA';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='PC';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='PD';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='PE';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='PG';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='PI';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='PN';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='PR';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='PS';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='PT';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='PV';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='PO';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='PZ';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='RA';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='RC';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='RE';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='RG';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='RI';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='RM';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='RN';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='RO';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='SA';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='SI';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='SO';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='SP';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='SR';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='SS';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='SV';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='TA';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='TE';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='TN';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='TO';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='TP';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='TR';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='TS';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='TV';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='UD';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='VA';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='VC';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='VE';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='VI';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='VP';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='VR';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='VT';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IT' AND zn_code='VV';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='ALD';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='ARM';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='ATM';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='BDS';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='BFD';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='BIR';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='BLG';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='BRI';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='BRK';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='BRS';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='BUX';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='CAP';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='CAR';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='CAS';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='CBA';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='CBE';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='CER';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='CHI';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='CHS';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='CLD';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='CNL';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='CON';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='CTR';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='CVE';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='DEN';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='DFD';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='DGL';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='DHM';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='DOR';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='DVN';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='DWN';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='DYS';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='ESX';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='FER';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='FFE';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='FLI';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='FMH';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='GDD';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='GLO';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='GLR';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='GNM';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='GNS';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='GNW';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='GRN';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='GUR';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='GWT';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='HBS';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='HFD';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='HLD';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='HPH';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='HWR';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='IOM';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='IOW';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='ISL';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='JER';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='KNT';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='LCN';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='LDN';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='LDR';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='LEC';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='LNH';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='LON';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='LTE';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='LTM';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='LTW';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='MCH';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='MER';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='MON';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='MSY';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='NET';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='NEW';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='NHM';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='NLD';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='NOR';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='NOT';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='NWH';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='OFE';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='ORK';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='PEM';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='PWS';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='SCD';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='SFD';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='SFK';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='SLD';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='SOM';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='SPE';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='SRK';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='SRY';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='SWA';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='SXE';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='SXW';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='TAF';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='TOR';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='TWR';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='TYR';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='TYS';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='VAL';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='WIL';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='WKS';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='WLT';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='WMD';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='WRE';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='YSN';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='YSS';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='GB' AND zn_code='YSW';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IE' AND zn_code='CAR';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IE' AND zn_code='CAV';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IE' AND zn_code='CLA';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IE' AND zn_code='COR';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IE' AND zn_code='DON';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IE' AND zn_code='DUB';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IE' AND zn_code='GAL';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IE' AND zn_code='KER';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IE' AND zn_code='KIL';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IE' AND zn_code='KLK';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IE' AND zn_code='LAO';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IE' AND zn_code='LEI';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IE' AND zn_code='LIM';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IE' AND zn_code='LON';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IE' AND zn_code='LOU';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IE' AND zn_code='MAY';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IE' AND zn_code='MEA';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IE' AND zn_code='MON';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IE' AND zn_code='OFF';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IE' AND zn_code='ROS';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IE' AND zn_code='SLI';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IE' AND zn_code='TIP';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IE' AND zn_code='WAT';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IE' AND zn_code='WES';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IE' AND zn_code='WEX';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='IE' AND zn_code='WIC';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='BR' AND zn_code='AC';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='BR' AND zn_code='AP';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='BR' AND zn_code='AL';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='BR' AND zn_code='AM';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='BR' AND zn_code='BA';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='BR' AND zn_code='CE';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='BR' AND zn_code='DF';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='BR' AND zn_code='ES';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='BR' AND zn_code='GO';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='BR' AND zn_code='MA';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='BR' AND zn_code='MG';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='BR' AND zn_code='MS';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='BR' AND zn_code='MT';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='BR' AND zn_code='PA';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='BR' AND zn_code='PB';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='BR' AND zn_code='PE';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='BR' AND zn_code='PI';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='BR' AND zn_code='PR';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='BR' AND zn_code='RJ';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='BR' AND zn_code='RN';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='BR' AND zn_code='RO';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='BR' AND zn_code='RR';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='BR' AND zn_code='RS';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='BR' AND zn_code='SC';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='BR' AND zn_code='SE';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='BR' AND zn_code='SP';
UPDATE static_country_zones SET zn_name_ru='' WHERE zn_country_iso_2='BR' AND zn_code='TO';


## static_currencies
UPDATE static_currencies SET cu_name_ru='Дирхам (ОАЭ)',cu_sub_name_ru='' WHERE cu_iso_3='AED';
UPDATE static_currencies SET cu_name_ru='Лек',cu_sub_name_ru='' WHERE cu_iso_3='ALL';
UPDATE static_currencies SET cu_name_ru='Армянский драм',cu_sub_name_ru='' WHERE cu_iso_3='AMD';
UPDATE static_currencies SET cu_name_ru='Нидерландский антильский гульден',cu_sub_name_ru='' WHERE cu_iso_3='ANG';
UPDATE static_currencies SET cu_name_ru='Кванза',cu_sub_name_ru='' WHERE cu_iso_3='AOA';
UPDATE static_currencies SET cu_name_ru='Аргентинское песо',cu_sub_name_ru='' WHERE cu_iso_3='ARS';
UPDATE static_currencies SET cu_name_ru='Австралийский доллар',cu_sub_name_ru='' WHERE cu_iso_3='AUD';
UPDATE static_currencies SET cu_name_ru='Арубанский гульден',cu_sub_name_ru='' WHERE cu_iso_3='AWG';
UPDATE static_currencies SET cu_name_ru='Азербайджанский манат',cu_sub_name_ru='' WHERE cu_iso_3='AZN';
UPDATE static_currencies SET cu_name_ru='Боснийская марка',cu_sub_name_ru='' WHERE cu_iso_3='BAM';
UPDATE static_currencies SET cu_name_ru='Барбадосский доллар',cu_sub_name_ru='' WHERE cu_iso_3='BBD';
UPDATE static_currencies SET cu_name_ru='Така',cu_sub_name_ru='' WHERE cu_iso_3='BDT';
UPDATE static_currencies SET cu_name_ru='Болгарский лев',cu_sub_name_ru='' WHERE cu_iso_3='BGN';
UPDATE static_currencies SET cu_name_ru='Бахрейнский динар',cu_sub_name_ru='' WHERE cu_iso_3='BHD';
UPDATE static_currencies SET cu_name_ru='Бурундийский франк',cu_sub_name_ru='' WHERE cu_iso_3='BIF';
UPDATE static_currencies SET cu_name_ru='Бермудский доллар',cu_sub_name_ru='' WHERE cu_iso_3='BMD';
UPDATE static_currencies SET cu_name_ru='Брунейский доллар',cu_sub_name_ru='' WHERE cu_iso_3='BND';
UPDATE static_currencies SET cu_name_ru='Боливиано',cu_sub_name_ru='' WHERE cu_iso_3='BOB';
UPDATE static_currencies SET cu_name_ru='Бразильский реал',cu_sub_name_ru='' WHERE cu_iso_3='BRL';
UPDATE static_currencies SET cu_name_ru='Багамский доллар',cu_sub_name_ru='' WHERE cu_iso_3='BSD';
UPDATE static_currencies SET cu_name_ru='Нгултрум',cu_sub_name_ru='' WHERE cu_iso_3='BTN';
UPDATE static_currencies SET cu_name_ru='Пула',cu_sub_name_ru='' WHERE cu_iso_3='BWP';
UPDATE static_currencies SET cu_name_ru='Белорусский рубль',cu_sub_name_ru='' WHERE cu_iso_3='BYR';
UPDATE static_currencies SET cu_name_ru='Белизский доллар',cu_sub_name_ru='' WHERE cu_iso_3='BZD';
UPDATE static_currencies SET cu_name_ru='Канадский доллар',cu_sub_name_ru='' WHERE cu_iso_3='CAD';
UPDATE static_currencies SET cu_name_ru='Конголезский франк',cu_sub_name_ru='' WHERE cu_iso_3='CDF';
UPDATE static_currencies SET cu_name_ru='Швейцарский франк',cu_sub_name_ru='' WHERE cu_iso_3='CHF';
UPDATE static_currencies SET cu_name_ru='Чилийское песо',cu_sub_name_ru='' WHERE cu_iso_3='CLP';
UPDATE static_currencies SET cu_name_ru='Юань Ренминби',cu_sub_name_ru='' WHERE cu_iso_3='CNY';
UPDATE static_currencies SET cu_name_ru='Колумбийское песо',cu_sub_name_ru='' WHERE cu_iso_3='COP';
UPDATE static_currencies SET cu_name_ru='Костариканский колон',cu_sub_name_ru='' WHERE cu_iso_3='CRC';
UPDATE static_currencies SET cu_name_ru='Кубинское песо',cu_sub_name_ru='' WHERE cu_iso_3='CUP';
UPDATE static_currencies SET cu_name_ru='Эскудо Кабо-Верде',cu_sub_name_ru='' WHERE cu_iso_3='CVE';
UPDATE static_currencies SET cu_name_ru='Кипрский фунт',cu_sub_name_ru='' WHERE cu_iso_3='CYP';
UPDATE static_currencies SET cu_name_ru='Чешская крона',cu_sub_name_ru='' WHERE cu_iso_3='CZK';
UPDATE static_currencies SET cu_name_ru='Франк Джибути',cu_sub_name_ru='' WHERE cu_iso_3='DJF';
UPDATE static_currencies SET cu_name_ru='Датская крона',cu_sub_name_ru='' WHERE cu_iso_3='DKK';
UPDATE static_currencies SET cu_name_ru='Доминиканское песо',cu_sub_name_ru='' WHERE cu_iso_3='DOP';
UPDATE static_currencies SET cu_name_ru='Алжирский динар',cu_sub_name_ru='' WHERE cu_iso_3='DZD';
UPDATE static_currencies SET cu_name_ru='Эстонская крона',cu_sub_name_ru='' WHERE cu_iso_3='EEK';
UPDATE static_currencies SET cu_name_ru='Египетский фунт',cu_sub_name_ru='' WHERE cu_iso_3='EGP';
UPDATE static_currencies SET cu_name_ru='Накфа',cu_sub_name_ru='' WHERE cu_iso_3='ERN';
UPDATE static_currencies SET cu_name_ru='Эфиопский быр',cu_sub_name_ru='' WHERE cu_iso_3='ETB';
UPDATE static_currencies SET cu_name_ru='Евро',cu_sub_name_ru='' WHERE cu_iso_3='EUR';
UPDATE static_currencies SET cu_name_ru='Доллар Фиджи',cu_sub_name_ru='' WHERE cu_iso_3='FJD';
UPDATE static_currencies SET cu_name_ru='Фунт Фолклендских островов',cu_sub_name_ru='' WHERE cu_iso_3='FKP';
UPDATE static_currencies SET cu_name_ru='Фунт стерлингов',cu_sub_name_ru='' WHERE cu_iso_3='GBP';
UPDATE static_currencies SET cu_name_ru='Лари',cu_sub_name_ru='' WHERE cu_iso_3='GEL';
UPDATE static_currencies SET cu_name_ru='Седи',cu_sub_name_ru='' WHERE cu_iso_3='GHC';
UPDATE static_currencies SET cu_name_ru='Гибралтарский фунт',cu_sub_name_ru='' WHERE cu_iso_3='GIP';
UPDATE static_currencies SET cu_name_ru='Даласи',cu_sub_name_ru='' WHERE cu_iso_3='GMD';
UPDATE static_currencies SET cu_name_ru='Гвинейский франк',cu_sub_name_ru='' WHERE cu_iso_3='GNF';
UPDATE static_currencies SET cu_name_ru='Кетсаль',cu_sub_name_ru='' WHERE cu_iso_3='GTQ';
UPDATE static_currencies SET cu_name_ru='Песо Гвинеи-Бисау',cu_sub_name_ru='' WHERE cu_iso_3='GWP';
UPDATE static_currencies SET cu_name_ru='Гайанский доллар',cu_sub_name_ru='' WHERE cu_iso_3='GYD';
UPDATE static_currencies SET cu_name_ru='Гонконгский доллар',cu_sub_name_ru='' WHERE cu_iso_3='HKD';
UPDATE static_currencies SET cu_name_ru='Лемпира',cu_sub_name_ru='' WHERE cu_iso_3='HNL';
UPDATE static_currencies SET cu_name_ru='Куна',cu_sub_name_ru='' WHERE cu_iso_3='HRK';
UPDATE static_currencies SET cu_name_ru='Гурд',cu_sub_name_ru='' WHERE cu_iso_3='HTG';
UPDATE static_currencies SET cu_name_ru='Форинт',cu_sub_name_ru='' WHERE cu_iso_3='HUF';
UPDATE static_currencies SET cu_name_ru='Рупия',cu_sub_name_ru='' WHERE cu_iso_3='IDR';
UPDATE static_currencies SET cu_name_ru='Новый израильский шекель',cu_sub_name_ru='' WHERE cu_iso_3='ILS';
UPDATE static_currencies SET cu_name_ru='Индийская рупия',cu_sub_name_ru='' WHERE cu_iso_3='INR';
UPDATE static_currencies SET cu_name_ru='Иракский динар',cu_sub_name_ru='' WHERE cu_iso_3='IQD';
UPDATE static_currencies SET cu_name_ru='Иранский риал',cu_sub_name_ru='' WHERE cu_iso_3='IRR';
UPDATE static_currencies SET cu_name_ru='Исландская крона',cu_sub_name_ru='' WHERE cu_iso_3='ISK';
UPDATE static_currencies SET cu_name_ru='Ямайский доллар',cu_sub_name_ru='' WHERE cu_iso_3='JMD';
UPDATE static_currencies SET cu_name_ru='Иорданский динар',cu_sub_name_ru='' WHERE cu_iso_3='JOD';
UPDATE static_currencies SET cu_name_ru='Йена',cu_sub_name_ru='' WHERE cu_iso_3='JPY';
UPDATE static_currencies SET cu_name_ru='Кенийский шиллинг',cu_sub_name_ru='' WHERE cu_iso_3='KES';
UPDATE static_currencies SET cu_name_ru='Сом',cu_sub_name_ru='' WHERE cu_iso_3='KGS';
UPDATE static_currencies SET cu_name_ru='Риель',cu_sub_name_ru='' WHERE cu_iso_3='KHR';
UPDATE static_currencies SET cu_name_ru='Франк Коморских островов',cu_sub_name_ru='' WHERE cu_iso_3='KMF';
UPDATE static_currencies SET cu_name_ru='Северо-корейская вона',cu_sub_name_ru='' WHERE cu_iso_3='KPW';
UPDATE static_currencies SET cu_name_ru='Вона',cu_sub_name_ru='' WHERE cu_iso_3='KRW';
UPDATE static_currencies SET cu_name_ru='Кувейтский динар',cu_sub_name_ru='' WHERE cu_iso_3='KWD';
UPDATE static_currencies SET cu_name_ru='Доллар Каймановых островов',cu_sub_name_ru='' WHERE cu_iso_3='KYD';
UPDATE static_currencies SET cu_name_ru='Тенге',cu_sub_name_ru='' WHERE cu_iso_3='KZT';
UPDATE static_currencies SET cu_name_ru='Кип',cu_sub_name_ru='' WHERE cu_iso_3='LAK';
UPDATE static_currencies SET cu_name_ru='Ливанский фунт',cu_sub_name_ru='' WHERE cu_iso_3='LBP';
UPDATE static_currencies SET cu_name_ru='Шри-Ланкийская рупия',cu_sub_name_ru='' WHERE cu_iso_3='LKR';
UPDATE static_currencies SET cu_name_ru='Либерийский доллар',cu_sub_name_ru='' WHERE cu_iso_3='LRD';
UPDATE static_currencies SET cu_name_ru='Лоти',cu_sub_name_ru='' WHERE cu_iso_3='LSL';
UPDATE static_currencies SET cu_name_ru='Литовский лит',cu_sub_name_ru='' WHERE cu_iso_3='LTL';
UPDATE static_currencies SET cu_name_ru='Латвийский лат',cu_sub_name_ru='' WHERE cu_iso_3='LVL';
UPDATE static_currencies SET cu_name_ru='Ливийский динар',cu_sub_name_ru='' WHERE cu_iso_3='LYD';
UPDATE static_currencies SET cu_name_ru='Марокканский дирхам',cu_sub_name_ru='' WHERE cu_iso_3='MAD';
UPDATE static_currencies SET cu_name_ru='Молдавский лей',cu_sub_name_ru='' WHERE cu_iso_3='MDL';
UPDATE static_currencies SET cu_name_ru='Динар',cu_sub_name_ru='' WHERE cu_iso_3='MKD';
UPDATE static_currencies SET cu_name_ru='Кьят',cu_sub_name_ru='' WHERE cu_iso_3='MMK';
UPDATE static_currencies SET cu_name_ru='Тугрик',cu_sub_name_ru='' WHERE cu_iso_3='MNT';
UPDATE static_currencies SET cu_name_ru='Патака',cu_sub_name_ru='' WHERE cu_iso_3='MOP';
UPDATE static_currencies SET cu_name_ru='Угия',cu_sub_name_ru='' WHERE cu_iso_3='MRO';
UPDATE static_currencies SET cu_name_ru='Мальтийская лира',cu_sub_name_ru='' WHERE cu_iso_3='MTL';
UPDATE static_currencies SET cu_name_ru='Маврикийская рупия',cu_sub_name_ru='' WHERE cu_iso_3='MUR';
UPDATE static_currencies SET cu_name_ru='Руфия',cu_sub_name_ru='' WHERE cu_iso_3='MVR';
UPDATE static_currencies SET cu_name_ru='Квача',cu_sub_name_ru='' WHERE cu_iso_3='MWK';
UPDATE static_currencies SET cu_name_ru='Мексиканское песо',cu_sub_name_ru='' WHERE cu_iso_3='MXN';
UPDATE static_currencies SET cu_name_ru='Малайзийский рингтит',cu_sub_name_ru='' WHERE cu_iso_3='MYR';
UPDATE static_currencies SET cu_name_ru='Метикал',cu_sub_name_ru='' WHERE cu_iso_3='MZM';
UPDATE static_currencies SET cu_name_ru='Доллар Намибии',cu_sub_name_ru='' WHERE cu_iso_3='NAD';
UPDATE static_currencies SET cu_name_ru='Найра',cu_sub_name_ru='' WHERE cu_iso_3='NGN';
UPDATE static_currencies SET cu_name_ru='Золотая кордоба',cu_sub_name_ru='' WHERE cu_iso_3='NIO';
UPDATE static_currencies SET cu_name_ru='Норвежская крона',cu_sub_name_ru='' WHERE cu_iso_3='NOK';
UPDATE static_currencies SET cu_name_ru='Непальская рупия',cu_sub_name_ru='' WHERE cu_iso_3='NPR';
UPDATE static_currencies SET cu_name_ru='Новозеландский доллар',cu_sub_name_ru='' WHERE cu_iso_3='NZD';
UPDATE static_currencies SET cu_name_ru='Оманский риал',cu_sub_name_ru='' WHERE cu_iso_3='OMR';
UPDATE static_currencies SET cu_name_ru='Бальбоа',cu_sub_name_ru='' WHERE cu_iso_3='PAB';
UPDATE static_currencies SET cu_name_ru='Новый соль',cu_sub_name_ru='' WHERE cu_iso_3='PEN';
UPDATE static_currencies SET cu_name_ru='Кина',cu_sub_name_ru='' WHERE cu_iso_3='PGK';
UPDATE static_currencies SET cu_name_ru='Филиппинское песо',cu_sub_name_ru='' WHERE cu_iso_3='PHP';
UPDATE static_currencies SET cu_name_ru='Пакистанская рупия',cu_sub_name_ru='' WHERE cu_iso_3='PKR';
UPDATE static_currencies SET cu_name_ru='Злотый',cu_sub_name_ru='' WHERE cu_iso_3='PLN';
UPDATE static_currencies SET cu_name_ru='Гуарани',cu_sub_name_ru='' WHERE cu_iso_3='PYG';
UPDATE static_currencies SET cu_name_ru='Катарский риал',cu_sub_name_ru='' WHERE cu_iso_3='QAR';
UPDATE static_currencies SET cu_name_ru='Лей',cu_sub_name_ru='' WHERE cu_iso_3='ROL';
UPDATE static_currencies SET cu_name_ru='Российский рубль',cu_sub_name_ru='' WHERE cu_iso_3='RUB';
UPDATE static_currencies SET cu_name_ru='Франк Руанды',cu_sub_name_ru='' WHERE cu_iso_3='RWF';
UPDATE static_currencies SET cu_name_ru='Саудовский риял',cu_sub_name_ru='' WHERE cu_iso_3='SAR';
UPDATE static_currencies SET cu_name_ru='Доллар Соломоновых островов',cu_sub_name_ru='' WHERE cu_iso_3='SBD';
UPDATE static_currencies SET cu_name_ru='Сейшельская рупия',cu_sub_name_ru='' WHERE cu_iso_3='SCR';
UPDATE static_currencies SET cu_name_ru='Суданский динар',cu_sub_name_ru='' WHERE cu_iso_3='SDD';
UPDATE static_currencies SET cu_name_ru='Шведская крона',cu_sub_name_ru='' WHERE cu_iso_3='SEK';
UPDATE static_currencies SET cu_name_ru='Сингапурский доллар',cu_sub_name_ru='' WHERE cu_iso_3='SGD';
UPDATE static_currencies SET cu_name_ru='Фунт Острова Святой Елены',cu_sub_name_ru='' WHERE cu_iso_3='SHP';
UPDATE static_currencies SET cu_name_ru='Толар',cu_sub_name_ru='' WHERE cu_iso_3='SIT';
UPDATE static_currencies SET cu_name_ru='Словацкая крона',cu_sub_name_ru='' WHERE cu_iso_3='SKK';
UPDATE static_currencies SET cu_name_ru='Леоне',cu_sub_name_ru='' WHERE cu_iso_3='SLL';
UPDATE static_currencies SET cu_name_ru='Сомалийский шиллинг',cu_sub_name_ru='' WHERE cu_iso_3='SOS';
UPDATE static_currencies SET cu_name_ru='Добра',cu_sub_name_ru='' WHERE cu_iso_3='STD';
UPDATE static_currencies SET cu_name_ru='Сальвадорский колон',cu_sub_name_ru='' WHERE cu_iso_3='SVC';
UPDATE static_currencies SET cu_name_ru='Сирийский фунт',cu_sub_name_ru='' WHERE cu_iso_3='SYP';
UPDATE static_currencies SET cu_name_ru='Лилангени',cu_sub_name_ru='' WHERE cu_iso_3='SZL';
UPDATE static_currencies SET cu_name_ru='Бат',cu_sub_name_ru='' WHERE cu_iso_3='THB';
UPDATE static_currencies SET cu_name_ru='Сомони',cu_sub_name_ru='' WHERE cu_iso_3='TJS';
UPDATE static_currencies SET cu_name_ru='Манат',cu_sub_name_ru='' WHERE cu_iso_3='TMM';
UPDATE static_currencies SET cu_name_ru='Тунисский динар',cu_sub_name_ru='' WHERE cu_iso_3='TND';
UPDATE static_currencies SET cu_name_ru='Паанга',cu_sub_name_ru='' WHERE cu_iso_3='TOP';
UPDATE static_currencies SET cu_name_ru='Доллар Тринидада и Тобаго',cu_sub_name_ru='' WHERE cu_iso_3='TTD';
UPDATE static_currencies SET cu_name_ru='Новый тайваньский доллар',cu_sub_name_ru='' WHERE cu_iso_3='TWD';
UPDATE static_currencies SET cu_name_ru='Танзанийский шиллинг',cu_sub_name_ru='' WHERE cu_iso_3='TZS';
UPDATE static_currencies SET cu_name_ru='Гривна',cu_sub_name_ru='' WHERE cu_iso_3='UAH';
UPDATE static_currencies SET cu_name_ru='Угандийский шиллинг',cu_sub_name_ru='' WHERE cu_iso_3='UGX';
UPDATE static_currencies SET cu_name_ru='Доллар США',cu_sub_name_ru='' WHERE cu_iso_3='USD';
UPDATE static_currencies SET cu_name_ru='Уругвайское песо',cu_sub_name_ru='' WHERE cu_iso_3='UYU';
UPDATE static_currencies SET cu_name_ru='Узбекский сум',cu_sub_name_ru='' WHERE cu_iso_3='UZS';
UPDATE static_currencies SET cu_name_ru='Боливар',cu_sub_name_ru='' WHERE cu_iso_3='VEB';
UPDATE static_currencies SET cu_name_ru='Донг',cu_sub_name_ru='' WHERE cu_iso_3='VND';
UPDATE static_currencies SET cu_name_ru='Вату',cu_sub_name_ru='' WHERE cu_iso_3='VUV';
UPDATE static_currencies SET cu_name_ru='Тала',cu_sub_name_ru='' WHERE cu_iso_3='WST';
UPDATE static_currencies SET cu_name_ru='Франк КФА ВЕАС',cu_sub_name_ru='' WHERE cu_iso_3='XAF';
UPDATE static_currencies SET cu_name_ru='Восточно-карибский доллар',cu_sub_name_ru='' WHERE cu_iso_3='XCD';
UPDATE static_currencies SET cu_name_ru='Франк КФА ВСЕАО',cu_sub_name_ru='' WHERE cu_iso_3='XOF';
UPDATE static_currencies SET cu_name_ru='Франк КФП',cu_sub_name_ru='' WHERE cu_iso_3='XPF';
UPDATE static_currencies SET cu_name_ru='Йеменский риал',cu_sub_name_ru='' WHERE cu_iso_3='YER';
UPDATE static_currencies SET cu_name_ru='Рэнд',cu_sub_name_ru='' WHERE cu_iso_3='ZAR';
UPDATE static_currencies SET cu_name_ru='Квача (замбийская)',cu_sub_name_ru='' WHERE cu_iso_3='ZMK';
UPDATE static_currencies SET cu_name_ru='Доллар Зимбабве',cu_sub_name_ru='' WHERE cu_iso_3='ZWD';
UPDATE static_currencies SET cu_name_ru='Афгани',cu_sub_name_ru='' WHERE cu_iso_3='AFN';
UPDATE static_currencies SET cu_name_ru='Сербский динар',cu_sub_name_ru='' WHERE cu_iso_3='CSD';
UPDATE static_currencies SET cu_name_ru='Малагасийский франк',cu_sub_name_ru='' WHERE cu_iso_3='MGA';
UPDATE static_currencies SET cu_name_ru='Суринамский доллар',cu_sub_name_ru='' WHERE cu_iso_3='SRD';
UPDATE static_currencies SET cu_name_ru='Турецкая лира',cu_sub_name_ru='' WHERE cu_iso_3='TRY';


## static_languages
UPDATE static_languages SET lg_name_ru='Абхазский' WHERE lg_iso_2='AB' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Афар' WHERE lg_iso_2='AA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Африкаанс' WHERE lg_iso_2='AF' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Албанский' WHERE lg_iso_2='SQ' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Амхарский' WHERE lg_iso_2='AM' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Арабский' WHERE lg_iso_2='AR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Армянский' WHERE lg_iso_2='HY' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Ассамский' WHERE lg_iso_2='AS' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Аймара' WHERE lg_iso_2='AY' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Азербайджанский' WHERE lg_iso_2='AZ' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Башкирский' WHERE lg_iso_2='BA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Баскский' WHERE lg_iso_2='EU' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Бенгальский' WHERE lg_iso_2='BN' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Дзонг-кэ' WHERE lg_iso_2='DZ' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Бихари' WHERE lg_iso_2='BH' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Бислама' WHERE lg_iso_2='BI' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Бретонский' WHERE lg_iso_2='BR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Болгарский' WHERE lg_iso_2='BG' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Бирманский' WHERE lg_iso_2='MY' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Белорусский' WHERE lg_iso_2='BE' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Кхмерский' WHERE lg_iso_2='KM' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Каталанский' WHERE lg_iso_2='CA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Чжуань' WHERE lg_iso_2='ZA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Китайский' WHERE lg_iso_2='ZH' AND lg_country_iso_2='HK';
UPDATE static_languages SET lg_name_ru='Корсиканский' WHERE lg_iso_2='CO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Хорватский' WHERE lg_iso_2='HR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Чешский' WHERE lg_iso_2='CS' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Датский' WHERE lg_iso_2='DA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Нидерландский' WHERE lg_iso_2='NL' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Английский' WHERE lg_iso_2='EN' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Эсперанто' WHERE lg_iso_2='EO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Эстонский' WHERE lg_iso_2='ET' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Фарерский' WHERE lg_iso_2='FO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Персидский' WHERE lg_iso_2='FA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Фиджи' WHERE lg_iso_2='FJ' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Финский' WHERE lg_iso_2='FI' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Французский' WHERE lg_iso_2='FR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Фризский' WHERE lg_iso_2='FY' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Галисийский' WHERE lg_iso_2='GL' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Шотландский' WHERE lg_iso_2='GD' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Мэнский' WHERE lg_iso_2='GV' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Грузинский' WHERE lg_iso_2='KA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Немецкий' WHERE lg_iso_2='DE' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Греческий' WHERE lg_iso_2='EL' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Калмыцкий' WHERE lg_iso_2='KL' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Гуарани' WHERE lg_iso_2='GN' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Гуджарати' WHERE lg_iso_2='GU' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Хауса' WHERE lg_iso_2='HA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Иврит' WHERE lg_iso_2='HE' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Хинди' WHERE lg_iso_2='HI' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Венгерский' WHERE lg_iso_2='HU' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Исландский' WHERE lg_iso_2='IS' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Индонезийский' WHERE lg_iso_2='ID' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Инуктитут' WHERE lg_iso_2='IU' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Инупиак' WHERE lg_iso_2='IK' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Ирландский' WHERE lg_iso_2='GA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Итальянский' WHERE lg_iso_2='IT' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Японский' WHERE lg_iso_2='JA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Каннада' WHERE lg_iso_2='KN' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Кашмири' WHERE lg_iso_2='KS' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Казахский' WHERE lg_iso_2='KK' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Киньяруанда' WHERE lg_iso_2='RW' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Киргизский' WHERE lg_iso_2='KY' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Рунди' WHERE lg_iso_2='RN' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Корейский' WHERE lg_iso_2='KO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Курдский' WHERE lg_iso_2='KU' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Лаосский' WHERE lg_iso_2='LO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Латышский' WHERE lg_iso_2='LV' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Лингала' WHERE lg_iso_2='LN' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Литовский' WHERE lg_iso_2='LT' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Македонский' WHERE lg_iso_2='MK' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Малагасийский' WHERE lg_iso_2='MG' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Малайский' WHERE lg_iso_2='MS' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Малаялям' WHERE lg_iso_2='ML' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Мальтийский' WHERE lg_iso_2='MT' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Маори' WHERE lg_iso_2='MI' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Маратхи' WHERE lg_iso_2='MR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Молдавский' WHERE lg_iso_2='MO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Монгольский' WHERE lg_iso_2='MN' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Науру' WHERE lg_iso_2='NA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Непальский' WHERE lg_iso_2='NE' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Норвежский' WHERE lg_iso_2='NO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Окситанский' WHERE lg_iso_2='OC' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Ория' WHERE lg_iso_2='OR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Оромо' WHERE lg_iso_2='OM' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Пушту' WHERE lg_iso_2='PS' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Польский' WHERE lg_iso_2='PL' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Португальский' WHERE lg_iso_2='PT' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Панджаби' WHERE lg_iso_2='PA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Кечуа' WHERE lg_iso_2='QU' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Ретороманский' WHERE lg_iso_2='RM' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Румынский' WHERE lg_iso_2='RO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Русский' WHERE lg_iso_2='RU' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Самоанский' WHERE lg_iso_2='SM' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Санго' WHERE lg_iso_2='SG' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Сербский' WHERE lg_iso_2='SR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Сото Южный' WHERE lg_iso_2='ST' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Тсвана' WHERE lg_iso_2='TN' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Шона' WHERE lg_iso_2='SN' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Синдхи' WHERE lg_iso_2='SD' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Сингальский' WHERE lg_iso_2='SI' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Свази' WHERE lg_iso_2='SS' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Словацкий' WHERE lg_iso_2='SK' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Словенский' WHERE lg_iso_2='SL' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Сомали' WHERE lg_iso_2='SO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Испанский' WHERE lg_iso_2='ES' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Сунданский' WHERE lg_iso_2='SU' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Суахили' WHERE lg_iso_2='SW' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Шведский' WHERE lg_iso_2='SV' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Тагальский' WHERE lg_iso_2='TL' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Таджикский' WHERE lg_iso_2='TG' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Тамильский' WHERE lg_iso_2='TA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Татарский' WHERE lg_iso_2='TT' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Телугу' WHERE lg_iso_2='TE' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Тайский' WHERE lg_iso_2='TH' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Тибетский' WHERE lg_iso_2='BO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Тигринья' WHERE lg_iso_2='TI' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Тонга (Тонга Исландский)' WHERE lg_iso_2='TO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Тсонга' WHERE lg_iso_2='TS' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Турецкий' WHERE lg_iso_2='TR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Туркменский' WHERE lg_iso_2='TK' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Тви' WHERE lg_iso_2='TW' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Уйгурский' WHERE lg_iso_2='UG' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Украинский' WHERE lg_iso_2='UK' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Урду' WHERE lg_iso_2='UR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Узбекский' WHERE lg_iso_2='UZ' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Вьетнамский' WHERE lg_iso_2='VI' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Валлийский (Уэльский)' WHERE lg_iso_2='CY' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Волоф' WHERE lg_iso_2='WO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Коса' WHERE lg_iso_2='XH' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Йоруба' WHERE lg_iso_2='YO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Зулу' WHERE lg_iso_2='ZU' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Боснийский' WHERE lg_iso_2='BS' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Акан' WHERE lg_iso_2='AK' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Арагонский' WHERE lg_iso_2='AN' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Аварский' WHERE lg_iso_2='AV' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Бамбара' WHERE lg_iso_2='BM' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Чеченский' WHERE lg_iso_2='CE' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Чаморро' WHERE lg_iso_2='CH' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Кри' WHERE lg_iso_2='CR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Чувашский' WHERE lg_iso_2='CV' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Дивехи (Мальдивский)' WHERE lg_iso_2='DV' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Эве' WHERE lg_iso_2='EE' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Фулах' WHERE lg_iso_2='FF' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Хиримоту' WHERE lg_iso_2='HO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Гаитянский' WHERE lg_iso_2='HT' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Гереро' WHERE lg_iso_2='HZ' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Игбо' WHERE lg_iso_2='IG' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Сычуань' WHERE lg_iso_2='II' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Конго' WHERE lg_iso_2='KG' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Кикуйю' WHERE lg_iso_2='KI' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Киньяма' WHERE lg_iso_2='KJ' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Канури' WHERE lg_iso_2='KR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Коми' WHERE lg_iso_2='KV' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Корнский' WHERE lg_iso_2='KW' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Люксембургский' WHERE lg_iso_2='LB' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Ганда' WHERE lg_iso_2='LG' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Лимбургийский' WHERE lg_iso_2='LI' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Луба-Катанга' WHERE lg_iso_2='LU' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Маршальский' WHERE lg_iso_2='MH' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Норвежский бокмол' WHERE lg_iso_2='NB' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Ндебеле северный' WHERE lg_iso_2='ND' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Ндунга' WHERE lg_iso_2='NG' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Нюнорск (Новонорвежский)' WHERE lg_iso_2='NN' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Ндебеле южный' WHERE lg_iso_2='NR' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Навахо' WHERE lg_iso_2='NV' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Ньянджа' WHERE lg_iso_2='NY' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Оджибва' WHERE lg_iso_2='OJ' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Осетинский' WHERE lg_iso_2='OS' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Сардинский' WHERE lg_iso_2='SC' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Северо-саамский' WHERE lg_iso_2='SE' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Таитянский' WHERE lg_iso_2='TY' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Венда' WHERE lg_iso_2='VE' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Валлонский' WHERE lg_iso_2='WA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Яванский' WHERE lg_iso_2='JV' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Португальский' WHERE lg_iso_2='PT' AND lg_country_iso_2='BR';
UPDATE static_languages SET lg_name_ru='Китайский' WHERE lg_iso_2='ZH' AND lg_country_iso_2='CN';
UPDATE static_languages SET lg_name_ru='Интерлингва' WHERE lg_iso_2='IA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Интерлингве' WHERE lg_iso_2='IE' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Латинский' WHERE lg_iso_2='LA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Санскрит' WHERE lg_iso_2='SA' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Волапюк' WHERE lg_iso_2='VO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Идиш' WHERE lg_iso_2='YI' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Авестийский' WHERE lg_iso_2='AE' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Церковно-славянский' WHERE lg_iso_2='CU' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Идо' WHERE lg_iso_2='IO' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='Пали' WHERE lg_iso_2='PI' AND lg_country_iso_2='';
UPDATE static_languages SET lg_name_ru='канадский французский' WHERE lg_iso_2='FR' AND lg_country_iso_2='CA';
UPDATE static_languages SET lg_name_ru='Филиппинский' WHERE lg_iso_2='TL' AND lg_country_iso_2='PH';
UPDATE static_languages SET lg_name_ru='черногорец' WHERE lg_iso_2='SR' AND lg_country_iso_2='ME';
